### 데이터 불러오기

In [ ]:
# setup
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score
import random
import functools
random.seed(1117)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file1='/content/drive/Shareddrives/Spotify Recommendation/Train.csv'
file2='/content/drive/Shareddrives/Spotify Recommendation/Test.csv'

In [ ]:
train=pd.read_csv(file1)
test=pd.read_csv(file2)

In [ ]:
print("Train datasets shape:", train.shape)
print("Test datasets shape:", test.shape)

Train datasets shape: (1815, 11)
Test datasets shape: (202, 11)


In [ ]:
train_x = train.drop(train.columns[[0,10]], axis=1)
x_test = test.drop(test.columns[[0,10]], axis=1) 

In [ ]:
train_y = train.iloc[:,10]
y_test = test.iloc[:,10]

In [ ]:
train_y[train_y==1] # 1815개 중 918개
y_test[y_test==1] # 202개 중 102개
# over-sampling 진행 안 해도 되겠다고 판단함.

0      1
1      1
2      1
4      1
7      1
      ..
191    1
192    1
194    1
197    1
200    1
Name: target, Length: 102, dtype: int64

### Validation set 만들기 (0.2)


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(train_x, train_y, test_size=0.2, shuffle=True , random_state=42)

In [ ]:
print("Train_x datasets shape:", x_train.shape)
print("Valid_x datasets shape:", x_valid.shape)

Train_x datasets shape: (1452, 9)
Valid_x datasets shape: (363, 9)


### 함수 정의

In [ ]:
def get_clf_eval(y_test, y_pred):
    confusion = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    F1 = f1_score(y_test, y_pred)
    AUC = roc_auc_score(y_test, y_pred)
    print('오차행렬:\n', confusion)
    print('\n정확도: {:.4f}'.format(accuracy))
    print('정밀도: {:.4f}'.format(precision))
    print('재현율: {:.4f}'.format(recall))
    print('F1: {:.4f}'.format(F1))
    print('AUC: {:.4f}'.format(AUC))

### Logistic Regression model(LASSO) + GridSearchCV

: sigmoid 함수 사용. 결과 값 0,1로 반환.

: 가중치의 제곱의 합이 아닌 가중치의 합을 더한 값에 규제 강도를 곱하여 오차에 더한다.

: 어떤 가중치는 실제로 0이 된다. 모델에서 완전히 제외되는 특성이 생기는 것.

: F1: 0.6341



In [ ]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

In [ ]:
lasso=Lasso()
print(lasso.get_params().keys())

dict_keys(['alpha', 'copy_X', 'fit_intercept', 'max_iter', 'normalize', 'positive', 'precompute', 'random_state', 'selection', 'tol', 'warm_start'])


In [ ]:
lasso = Lasso(random_state=1, max_iter=10000)
alphas = np.logspace(-4, -0.5, 30)

tuned_parameters = [{'alpha': alphas}]
n_folds = 5

clf = GridSearchCV(lasso, tuned_parameters, cv=n_folds)
clf.fit(x_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=10000, normalize=False, positive=False,
                             precompute=False, random_state=1,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'alpha': array([1.00000000e-04, 1.32035178e-04, 1.74332882e-04, 2.30180731e-04,
       3.03919538e-04, 4...
       2.80721620e-03, 3.70651291e-03, 4.89390092e-03, 6.46167079e-03,
       8.53167852e-03, 1.12648169e-02, 1.48735211e-02, 1.96382800e-02,
       2.59294380e-02, 3.42359796e-02, 4.52035366e-02, 5.96845700e-02,
       7.88046282e-02, 1.04049831e-01, 1.37382380e-01, 1.81393069e-01,
       2.39502662e-01, 3.16227766e-01])}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
Lasso_best = clf.best_estimator_

In [ ]:
print(Lasso_best)

Lasso(alpha=0.0005298316906283707, copy_X=True, fit_intercept=True,
      max_iter=10000, normalize=False, positive=False, precompute=False,
      random_state=1, selection='cyclic', tol=0.0001, warm_start=False)


In [ ]:
y_pred = Lasso_best.predict(x_valid)
y_pred1=pd.Series(y_pred)
print(accuracy_score(y_valid, y_pred1.round()))

0.6528925619834711


In [ ]:
y_pred = Lasso_best.predict(x_test)
y_pred1=pd.Series(y_pred)

In [ ]:
print(accuracy_score(y_test, y_pred1.round()))
pd.crosstab(y_test, y_pred1, rownames = ["True"], colnames = ["Predicted"], margins = True)

0.6287128712871287


Predicted  0.17674827014595942  0.17825957532733208  ...  1.1283978703484312  All
True                                                 ...                         
0                            1                    1  ...                   0  100
1                            0                    0  ...                   1  102
All                          1                    1  ...                   1  202

[3 rows x 203 columns]

In [ ]:
get_clf_eval(y_test,y_pred1.round())

오차행렬:
 [[62 38]
 [37 65]]

정확도: 0.6287
정밀도: 0.6311
재현율: 0.6373
F1: 0.6341
AUC: 0.6286


### Logistic Regression model(RIDGE) + GridSearchCV
https://wikidocs.net/16594

:sigmoid 함수 사용. 결과 값 0,1로 반환.

: 각 가중치 제곱의 합에 규제 강도 (labmda) 곱함.

: lambda를 크게 하면 가중치가 더 많이 감소하고, lambda를 작게 하면 가중치가 증가한다.

: F1: 0.6381

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

In [ ]:
LR=LogisticRegression()

In [ ]:
print(LR.get_params().keys())

dict_keys(['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])


In [ ]:
from sklearn.model_selection import GridSearchCV

# 파라메터 후보
param_grid = {'C': [9.5,9.6,9.7,9.8,9.9,10,10.1,10.2,10.3,10.4,10.5],
              'penalty': ['l2']}

# 그리드 서치 진행

grid_search = GridSearchCV(LR, param_grid, cv=KFold(n_splits=10))

# 최종 모델 성능 점검

grid_search.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [9.5, 9.6, 9.7, 9.8, 9.9, 10, 10.1, 10.2, 10.3,
                               10.4, 10.5],
                         'penalty': ['l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
Ridge_best = grid_search.best_estimator_

In [ ]:
print(Ridge_best)

LogisticRegression(C=9.7, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


In [ ]:
y_pred = Ridge_best.predict(x_valid)
y_pred1=pd.Series(y_pred)
print(accuracy_score(y_valid, y_pred1.round()))

0.6584022038567493


In [ ]:
y_pred = Ridge_best.predict(x_test)
y_pred1=pd.Series(y_pred)

In [ ]:
print(accuracy_score(y_test, y_pred1.round()))
pd.crosstab(y_test, y_pred1, rownames = ["True"], colnames = ["Predicted"], margins = True)

0.6237623762376238


Predicted   0    1  All
True                   
0          59   41  100
1          35   67  102
All        94  108  202

In [ ]:
get_clf_eval(y_test,y_pred1.round())

오차행렬:
 [[59 41]
 [35 67]]

정확도: 0.6238
정밀도: 0.6204
재현율: 0.6569
F1: 0.6381
AUC: 0.6234


### Logistic Regression model(Elastic Net) + GridSearchCV

: F1: 0.6286

In [ ]:
from sklearn.linear_model import ElasticNet

In [ ]:
model=ElasticNet()

In [ ]:
print(model.get_params().keys())

dict_keys(['alpha', 'copy_X', 'fit_intercept', 'l1_ratio', 'max_iter', 'normalize', 'positive', 'precompute', 'random_state', 'selection', 'tol', 'warm_start'])


In [ ]:
# 파라메터 후보
param_grid = {'alpha': [0.0098,0.0099,0.001,0.002,0.003,0.004,0.005],'l1_ratio':[0.001,0.01,0.1,1]}

# 그리드 서치 진행

grid_search = GridSearchCV(model, param_grid, cv=KFold(n_splits=10))

In [ ]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             error_score=nan,
             estimator=ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True,
                                  l1_ratio=0.5, max_iter=1000, normalize=False,
                                  positive=False, precompute=False,
                                  random_state=None, selection='cyclic',
                                  tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [0.0098, 0.0099, 0.001, 0.002, 0.003, 0.004,
                                   0.005],
                         'l1_ratio': [0.001, 0.01, 0.1, 1]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
ElasticNet_best = grid_search.best_estimator_

In [ ]:
print(ElasticNet_best)

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.001,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)


In [ ]:
y_pred = ElasticNet_best.predict(x_valid)
y_pred1=pd.Series(y_pred)
print(accuracy_score(y_valid, y_pred1.round()))

0.6584022038567493


In [ ]:
print(ElasticNet_best)

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.001,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)


In [ ]:
y_pred = ElasticNet_best.predict(x_test)
y_pred1=pd.Series(y_pred)

In [ ]:
print(accuracy_score(y_test, y_pred1.round()))
pd.crosstab(y_test, y_pred1, rownames = ["True"], colnames = ["Predicted"], margins = True)

0.6138613861386139


Predicted  0.17457986592920038  0.17527187873593955  ...  1.1449962557462294  All
True                                                 ...                         
0                            1                    1  ...                   0  100
1                            0                    0  ...                   1  102
All                          1                    1  ...                   1  202

[3 rows x 203 columns]

In [ ]:
get_clf_eval(y_test,y_pred1.round())

오차행렬:
 [[58 42]
 [36 66]]

정확도: 0.6139
정밀도: 0.6111
재현율: 0.6471
F1: 0.6286
AUC: 0.6135


### Logistic Regreesion + Feature Selection (9개 중 5개) + grid_search(L2)

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif

selectK = SelectKBest(score_func=f_classif, k=5)
train_xK = selectK.fit_transform(train_x, train_y)
test_xK = selectK.fit_transform(x_test, y_test)

In [ ]:
grid_search.fit(train_xK,train_y)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             error_score=nan,
             estimator=ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True,
                                  l1_ratio=0.5, max_iter=1000, normalize=False,
                                  positive=False, precompute=False,
                                  random_state=None, selection='cyclic',
                                  tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'l1_ratio': [0.001, 0.01, 0.1, 1]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
Featureselection_best = grid_search.best_estimator_

In [ ]:
y_pred = Featureselection_best.predict(test_xK)
print(accuracy_score(y_test, y_pred.round()))
pd.crosstab(y_test, y_pred, rownames = ["True"], colnames = ["Predicted"], margins = True)

0.04950495049504951


Predicted  -8.232559259935083  -6.89926787596032  ...  0.31289060017258025  All
True                                              ...                          
0                           1                  0  ...                    1  100
1                           0                  1  ...                    0  102
All                         1                  1  ...                    1  202

[3 rows x 203 columns]